name = "Cobblemon WLWC"
author = "SillviaTV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98959273bb22859ea825579638b8abc785c77ff2880f2f00d6ce60cdf8adfd47"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
