name = "Cobblemon WLWC"
author = "SillviaTV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa8b2d16c78b6a51a968d3b95e2e3147e61b931a7228522a2952b75cdcd6cb65"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.218"
