general = {disable_mod = false, hide_bossbar = true, shadow_text = true, auto_start = false, animationSpeed = 1.0, always_show_ping = false, hide_debug_crosshair = false, background_color = 1867534416, space_modules = false, always_show_profiler = false, animations = true, fontScale = 1.0, hide_sidebar = true, always_show_tps = false}
modules_right = []
[[modules_left]]
	color_high = 5635925
	color_med = 16777045
	name = "fps"
	lines = {fps = true}
	enabled = true
	color_low = 16733525
[[modules_left]]
	empty_lines = 1
	name = "empty"
	lines = {nothing = true}
	enabled = true
[[modules_left]]
	name = "target"
	name_color = 43775
	value_color = 16777045
	lines = {id_fluid = true, fluid_tags = true, block_states = true, targeted_block = true, block_tags = true, id_block = true, nothing = true, nothing2 = true, targeted_fluid = true, targeted_entity = true, fluid_states = true}
	enabled = true
